### ISSUE TITLE
Edit script generation fails if input files have different parsers

### ISSUE THREAD

**Issue by snim2** [softdevteam/diffract#39]
This was discovered in PR #36 but reproducing does not require the `-g` switch, so the bug must have been in the code base for some time.

Example input files:

```
$ cat tests/add.calc
1+2

$ cat tests/Hello.txt
public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
```

Example run:

```
$ diffract -a -m Myers tests/add.calc tests/Hello.txt 

INFO:diffract: Selecting the Myers matching algorithm.
^~
 ~
 Expr
  Term
   Factor
    INT 1
    ~
  PLUS +
  ~
  Expr
   Term
    Factor
     INT 2
     ~
      WHITESPACE 

      ~

document
 paragraph
  WORD public
  SPACE  
  paragraph
   WORD class
   SPACE  
   paragraph
    WORD Hello
    SPACE  
    paragraph
     WORD {
 END 

 document
  paragraph
   SPACE     
   paragraph
    WORD public
    SPACE  
    paragraph
     WORD static
     SPACE  
     paragraph
      WORD void
      SPACE  
      paragraph
       WORD main(String[]
       SPACE  
       paragraph
        WORD args)
        SPACE  
        paragraph
         WORD {
  END 

  document
   paragraph
    SPACE         
    paragraph
     WORD System.out.println("Hello,
     SPACE  
     paragraph
      WORD world!");
   END 

   document
    paragraph
     SPACE     
     paragraph
      WORD }
    END 

    document
     paragraph
      WORD }
     END 


thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: <diffract::matchers::MappingStore<T>>::generate_edit_script
             at ./src/lib/matchers.rs:345
  12: diffract::main
             at src/main.rs:374
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  15: main
  16: __libc_start_main
```

**Comment by snim2** [comment]
So, although the crash here comes from the edit script generator, Diffract does not crash if we use a dummy matcher which just matches the root nodes of the two input ASTs. It's possible then that the issue is with the Myers matcher and not the edit script generator...

**Comment by snim2** [comment]
Possibly related to #41
